[project]
name = "GRASP"
version = "0.0.1"
authors = [
  { name="Gianluca Zavan", email="gianluca.zavan@aau.at" },
]
description = "A language to simplify the definition of rule rewritings for Answer Set Programming"
readme = "README.md"
requires-python = ">=3.13.0"
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/gianzav/GRASP"

[project.scripts]
grasp = "grasp.repl:main"